[build]
  command="ng build --outputHashing=all"
  publish="dist/client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.development]
  command="ng build --configuration=development --outputHashing=all"

[context.staging]
  command="ng build --configuration=staging --outputHashing=all"