[build]
  command="ng build"
  publish="dist/client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.development]
  command="ng build"
  base = "development"

[context.staging]
  command="ng build --configuration=staging"
  base = "staging"