[build]
  command="ng build --outputHashing=all"
  publish="dist/client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.development]
  command="ng build  --outputHashing=all --configuration=development"

[context.staging]
  command="ng build --outputHashing=all --configuration=staging"